import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./providers";
import MantineProvider from "./mantine-provider";
import NextThemeProvider from "./next-theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en-US" suppressHydrationWarning>
      <head />
      <body className={inter.className}>
        <NextThemeProvider>
          <MantineProvider>
            <Providers>{children}</Providers>
          </MantineProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
}
